GIT
ilanrosenfeld7/globant-bootcamps-java pull request #5
Opened 2018-09-14 21:13 UTC by claudiorave

7. Create a Pull Request against upstream master branch to include your group name and members in the README.md file. The PR must not have any conflicts. Every participant must create its own PR including his/her complete name and nickname.

2018-09-17 15:29 UTC, ilanrosenfeld7 commented
El nombre del PR debería ser más descriptivo

2018-09-17 15:30 UTC, ilanrosenfeld7 requested changes

2018-09-17 15:30 UTC, ilanrosenfeld7 commented on README.md
> +Group-1: Raverta, Claudio Marco (claudiorave). Perez, Jefferson.
"Every participant must create its own PR including his/her complete name and nickname."
Que figure solo tu nombre. Y Jefferson debería hacer su propio PR

2018-09-17 15:31 UTC, ilanrosenfeld7 commented on README.md
> +Group-1: Raverta, Claudio Marco (claudiorave). Perez, Jefferson.
Chequear que el PR de giorgio ya fue mergeado. Incluir esto bajo su comentario

2018-09-18 19:47 UTC, claudiorave commented
Ahí lo arregle!

2018-09-18 21:20 UTC, merged